name: Update Corporate Announcements Data

on:
  schedule:
    # Run every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Python dependencies
      run: |
        pip install selenium mistralai groq python-dotenv requests
        
    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: Run scraper
      env:
        MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        SCREENER_EMAIL: ${{ secrets.SCREENER_EMAIL }}
        SCREENER_PASSWORD: ${{ secrets.SCREENER_PASSWORD }}
      run: |
        timeout 600 python main.py || echo "Scraper completed or timed out"
        
    - name: Copy CSV to client public folder
      run: |
        cp catalyst-watch.csv client/public/
        
    - name: Commit and push if data changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --staged --quiet || git commit -m "Update corporate announcements data"
        git push 